'use strict';

module.exports = app => {
  const { STRING, INTEGER, BIGINT, BOOLEAN, DECIMAL, DATE } = app.Sequelize;

  const User = app.model.define('user', {
    id: {
      type: INTEGER.UNSIGNED,
      primaryKey: true,
      autoIncrement: true,
      field: 'id',
      comment: '主键ID',
    },
    user_id: {
      type: BIGINT.UNSIGNED,
      unique: true,
      field: 'user_code',
      comment: '用户ID（9-12位，对外展示）',
    },
    user_name: {
      type: STRING(64),
      unique: true,
      field: 'username',
      comment: '用户名，默认使用手机号',
    },
    user_nickname: {
      type: STRING(64),
      field: 'nickname',
      comment: '用户昵称',
    },
    user_password: {
      type: STRING(64),
      allowNull: false,
      field: 'password',
      comment: '登录密码',
    },
    user_email: {
      type: STRING(128),
      defaultValue: '',
      field: 'email',
      comment: '用户邮箱',
    },
    user_phone: {
      type: STRING(20),
      allowNull: false,
      unique: true,
      field: 'phone',
      comment: '手机号',
    },
    user_avatar: {
      type: STRING(255),
      defaultValue: '',
      field: 'avatar',
      comment: '用户头像',
    },
    user_withdraw_password: {
      type: STRING(255),
      allowNull: false,
      defaultValue: '',
      field: 'withdraw_password',
      comment: '提现密码',
    },
    user_vip: {
      type: INTEGER,
      allowNull: false,
      defaultValue: 1,
      field: 'vip_level',
      comment: 'VIP等级：1-vip1 2-vip2 3-vip3',
    },
    user_balance: {
      type: DECIMAL(12, 2),
      allowNull: false,
      defaultValue: 0.00,
      field: 'balance',
      comment: '用户余额',
    },
    user_frozen_amount: {
      type: DECIMAL(12, 2),
      allowNull: false,
      defaultValue: 0.00,
      field: 'frozen_amount',
      comment: '冻结金额',
    },
    user_status: {
      type: INTEGER.UNSIGNED,
      allowNull: false,
      defaultValue: 0,
      field: 'status',
      comment: '用户状态：0-正常 1-禁用',
    },
    user_address: {
      type: STRING(256),
      allowNull: false,
      defaultValue: '',
      field: 'user_address',
      comment: '用户地址',
    },
    user_ip: {
      type: STRING(64),
      defaultValue: '',
      field: 'register_ip',
      comment: '用户注册IP',
    },
    user_country: {
      type: STRING(128),
      defaultValue: '',
      field: 'register_location',
      comment: '用户注册国家/地区',
    },
    user_remark: {
      type: STRING(256),
      defaultValue: '',
      field: 'remark',
      comment: '用户备注',
    },
    user_invite_code: {
      type: STRING(64),
      unique: true,
      field: 'invite_code',
      comment: '用户邀请码',
    },
    user_referral_id: {
      type: BIGINT.UNSIGNED,
      allowNull: true,
      field: 'parent_id',
      comment: '推荐人ID（存储的是推荐人的 user_code）',
    },
    total_recharge_amount: {
      type: DECIMAL(12, 2),
      allowNull: false,
      defaultValue: 0.00,
      field: 'recharge_amount',
      comment: '用户总充值金额',
    },
    user_invite_income: {
      type: DECIMAL(12, 2),
      allowNull: false,
      defaultValue: 0.00,
      field: 'invite_income',
      comment: '用户邀请收入',
    },
    bind_admin_id: {
      type: BIGINT.UNSIGNED,
      allowNull: true,
      field: 'bind_admin_id',
      comment: '店铺ID/商户ID',
    },
    bind_salesperson_id: {
      type: INTEGER.UNSIGNED,
      allowNull: true,
      field: 'bind_salesperson_id',
      comment: '直属管理员ID',
    },
    admin_role: {
      type: INTEGER,
      allowNull: true,
      comment: '管理员角色',
    },
    is_real: {
      type: BOOLEAN,
      allowNull: false,
      defaultValue: true,
      comment: '是否真实用户，true：真实用户，false：虚拟用户',
    },
    has_recharged: {
      type: BOOLEAN,
      allowNull: false,
      defaultValue: false,
      field: 'has_recharged',
      comment: '是否充值过，false：未充值，true：已充值过',
    },
    coupon_balance: {
      type: DECIMAL(12, 2),
      allowNull: false,
      defaultValue: 0.00,
      field: 'voucher_balance',
      comment: '代金资产',
    },
    static_income: {
      type: DECIMAL(12, 2),
      allowNull: false,
      defaultValue: 0.00,
      comment: '静态收益',
    },
    dynamic_income: {
      type: DECIMAL(12, 2),
      allowNull: false,
      defaultValue: 0.00,
      comment: '动态收益',
    },
    withdrawal_status: {
      type: BOOLEAN,
      allowNull: false,
      defaultValue: true,
      field: 'withdraw_status',
      comment: '提现状态，false：不可提现，true：可以提现',
    },
    temp_withdraw_status: {
      type: BOOLEAN,
      allowNull: false,
      defaultValue: false,
      field: 'temp_withdraw',
      comment: '临时提现状态，false：关闭，true：开启',
    },
    user_level: {
      type: INTEGER.UNSIGNED,
      allowNull: false,
      defaultValue: 1,
      comment: '用户层级',
    },
    strategy_id: {
      type: INTEGER.UNSIGNED,
      allowNull: true,
      defaultValue: 0,
      comment: '绑定的策略ID',
    },
    is_task_started: {
      type: BOOLEAN,
      allowNull: false,
      defaultValue: false,
      comment: '任务是否开启：false-未开启 true-已开启',
    },
    user_create_time: {
      type: DATE,
      allowNull: false,
      defaultValue: app.Sequelize.literal('CURRENT_TIMESTAMP'),
      field: 'created_at',
      comment: '用户账号创建时间',
    },
    user_update_time: {
      type: DATE,
      allowNull: false,
      defaultValue: app.Sequelize.literal('CURRENT_TIMESTAMP'),
      field: 'updated_at',
      comment: '用户账号更新时间',
    },
  }, {
    tableName: 'users',
    comment: '用户表',
    timestamps: true,
    createdAt: 'created_at',
    updatedAt: 'updated_at',
  });

  return User;
};
