// This file is created by egg-ts-helper@2.1.1
// Do not modify this file!!!!!!!!!
/* eslint-disable */

import 'egg';
type AnyClass = new (...args: any[]) => any;
type AnyFunc<T = any> = (...args: any[]) => T;
type CanExportFunc = AnyFunc<Promise<any>> | AnyFunc<IterableIterator<any>>;
type AutoInstanceType<T, U = T extends CanExportFunc ? T : T extends AnyFunc ? ReturnType<T> : T> = U extends AnyClass ? InstanceType<U> : U;
import ExportAddress = require('../../../app/service/address');
import ExportAdminDashboard = require('../../../app/service/admin_dashboard');
import ExportAdminInnerUser = require('../../../app/service/admin_inner_user');
import ExportAdminOuterCustomer = require('../../../app/service/admin_outer_customer');
import ExportAdminOuterOrder = require('../../../app/service/admin_outer_order');
import ExportAdminOuterUser = require('../../../app/service/admin_outer_user');
import ExportAdminUser = require('../../../app/service/admin_user');
import ExportBackMoney = require('../../../app/service/back_money');
import ExportBanner = require('../../../app/service/banner');
import ExportCategory = require('../../../app/service/category');
import ExportCustomer = require('../../../app/service/customer');
import ExportCustomerService = require('../../../app/service/customer_service');
import ExportDashboard = require('../../../app/service/dashboard');
import ExportFundRecord = require('../../../app/service/fund_record');
import ExportGoods = require('../../../app/service/goods');
import ExportGoodsTask = require('../../../app/service/goods_task');
import ExportH5Config = require('../../../app/service/h5_config');
import ExportH5Service = require('../../../app/service/h5_service');
import ExportNotice = require('../../../app/service/notice');
import ExportOrder = require('../../../app/service/order');
import ExportPayChannel = require('../../../app/service/pay_channel');
import ExportPermission = require('../../../app/service/permission');
import ExportPointsDeduct = require('../../../app/service/points_deduct');
import ExportPointsGive = require('../../../app/service/points_give');
import ExportProduct = require('../../../app/service/product');
import ExportRecharge = require('../../../app/service/recharge');
import ExportRechargeRequest = require('../../../app/service/recharge_request');
import ExportRule = require('../../../app/service/rule');
import ExportSalesRechargeAddress = require('../../../app/service/sales_recharge_address');
import ExportShop = require('../../../app/service/shop');
import ExportShopConfig = require('../../../app/service/shop_config');
import ExportStats = require('../../../app/service/stats');
import ExportStrategy = require('../../../app/service/strategy');
import ExportSysConfig = require('../../../app/service/sys_config');
import ExportSysLog = require('../../../app/service/sys_log');
import ExportTask = require('../../../app/service/task');
import ExportTotp = require('../../../app/service/totp');
import ExportUpload = require('../../../app/service/upload');
import ExportUser = require('../../../app/service/user');
import ExportUserCredential = require('../../../app/service/user_credential');
import ExportVipLevel = require('../../../app/service/vip_level');
import ExportWithdraw = require('../../../app/service/withdraw');
import ExportWithdrawConfig = require('../../../app/service/withdraw_config');
import ExportWithdrawWay = require('../../../app/service/withdraw_way');

declare module 'egg' {
  interface IService {
    address: AutoInstanceType<typeof ExportAddress>;
    adminDashboard: AutoInstanceType<typeof ExportAdminDashboard>;
    adminInnerUser: AutoInstanceType<typeof ExportAdminInnerUser>;
    adminOuterCustomer: AutoInstanceType<typeof ExportAdminOuterCustomer>;
    adminOuterOrder: AutoInstanceType<typeof ExportAdminOuterOrder>;
    adminOuterUser: AutoInstanceType<typeof ExportAdminOuterUser>;
    adminUser: AutoInstanceType<typeof ExportAdminUser>;
    backMoney: AutoInstanceType<typeof ExportBackMoney>;
    banner: AutoInstanceType<typeof ExportBanner>;
    category: AutoInstanceType<typeof ExportCategory>;
    customer: AutoInstanceType<typeof ExportCustomer>;
    customerService: AutoInstanceType<typeof ExportCustomerService>;
    dashboard: AutoInstanceType<typeof ExportDashboard>;
    fundRecord: AutoInstanceType<typeof ExportFundRecord>;
    goods: AutoInstanceType<typeof ExportGoods>;
    goodsTask: AutoInstanceType<typeof ExportGoodsTask>;
    h5Config: AutoInstanceType<typeof ExportH5Config>;
    h5Service: AutoInstanceType<typeof ExportH5Service>;
    notice: AutoInstanceType<typeof ExportNotice>;
    order: AutoInstanceType<typeof ExportOrder>;
    payChannel: AutoInstanceType<typeof ExportPayChannel>;
    permission: AutoInstanceType<typeof ExportPermission>;
    pointsDeduct: AutoInstanceType<typeof ExportPointsDeduct>;
    pointsGive: AutoInstanceType<typeof ExportPointsGive>;
    product: AutoInstanceType<typeof ExportProduct>;
    recharge: AutoInstanceType<typeof ExportRecharge>;
    rechargeRequest: AutoInstanceType<typeof ExportRechargeRequest>;
    rule: AutoInstanceType<typeof ExportRule>;
    salesRechargeAddress: AutoInstanceType<typeof ExportSalesRechargeAddress>;
    shop: AutoInstanceType<typeof ExportShop>;
    shopConfig: AutoInstanceType<typeof ExportShopConfig>;
    stats: AutoInstanceType<typeof ExportStats>;
    strategy: AutoInstanceType<typeof ExportStrategy>;
    sysConfig: AutoInstanceType<typeof ExportSysConfig>;
    sysLog: AutoInstanceType<typeof ExportSysLog>;
    task: AutoInstanceType<typeof ExportTask>;
    totp: AutoInstanceType<typeof ExportTotp>;
    upload: AutoInstanceType<typeof ExportUpload>;
    user: AutoInstanceType<typeof ExportUser>;
    userCredential: AutoInstanceType<typeof ExportUserCredential>;
    vipLevel: AutoInstanceType<typeof ExportVipLevel>;
    withdraw: AutoInstanceType<typeof ExportWithdraw>;
    withdrawConfig: AutoInstanceType<typeof ExportWithdrawConfig>;
    withdrawWay: AutoInstanceType<typeof ExportWithdrawWay>;
  }
}
